---
title: "Alpha and Environmental predictors"
author: "Aidee Guzman"
date: "5/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE, cache=FALSE}
## Source for Analysis workflow 


## *******************************************************
## 1. load
## *******************************************************

source('/Volumes/GoogleDrive/My Drive/Research/Research projects/Spatial project/Analysis/R workflow/fungalcommunitycomp/R Scripts/load.R', chdir = TRUE)

source('/Volumes/GoogleDrive/My Drive/Research/Research projects/Spatial project/Analysis/R workflow/fungalcommunitycomp/R Scripts/functions.R', chdir = TRUE)


## *******************************************************
## 2. clean
## *******************************************************
source('/Volumes/GoogleDrive/My Drive/Research/Research projects/Spatial project/Analysis/R workflow/fungalcommunitycomp/R Scripts/clean.R', chdir = TRUE)

## *******************************************************
## 3. analysis
## *******************************************************
source('/Volumes/GoogleDrive/My Drive/Research/Research projects/Spatial project/Analysis/R workflow/fungalcommunitycomp/R Scripts/analysis.R', chdir = TRUE)

## *******************************************************
## 4. plots
## *******************************************************
source('/Volumes/GoogleDrive/My Drive/Research/Research projects/Spatial project/Analysis/R workflow/fungalcommunitycomp/R Scripts/plots.R', chdir = TRUE)

```



# Alpha 

**Tables** 
```{r, tidy=TRUE, echo=FALSE}
alphaSummary
alphaFTBLSummary
alphaBlockSummary
```

**Model output** 
```{r, tidy=TRUE, echo=FALSE}
alphaModels
```


**Plots** 
```{r, echo=FALSE, fig.height = 4, fig.width = 6, fig.align='center', message=FALSE}
richPlots
richBlockPlots
richFTBLPlots
```

\pagebreak  


# Alpha x Environment 

**Tables** 
```{r, tidy=TRUE, echo=FALSE}
alphaEnvSummary
alphaEnvFTBLSummary
alphaEnvBlockSummary
```

**Model output** 
```{r, tidy=TRUE, echo=FALSE}
# alphaModels
```


**Plots** 
```{r, echo=FALSE, fig.height = 4, fig.width = 6, fig.align='center', message=FALSE}
alpha_env(colNames=divIndices,expVar = "pH", color="FarmType",data = alphaDF)
alpha_env(colNames=divIndices,expVar = "P", color="FarmType",data = alphaDF)
alpha_env(colNames=divIndices,expVar = "TOC", color="FarmType",data = alphaDF)
alpha_env(colNames=divIndices,expVar = "N", color="FarmType",data = alphaDF)
alpha_env(colNames=divIndices,expVar = "NP_ratio", color="FarmType",data = alphaDF)

```

\pagebreak  
